name: CI/CD Pipeline for Dockerized Elasticsearch and EC2 Deployment

on: push

jobs:
  build-and-load:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker and Docker Compose on EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USER@$HOST "
            sudo yum update -y &&
            sudo yum install docker -y &&
            sudo systemctl start docker &&
            sudo systemctl enable docker &&
            sudo usermod -aG docker ec2-user &&
            sudo curl -L 'https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)' -o /usr/local/bin/docker-compose &&
            sudo chmod +x /usr/local/bin/docker-compose
          "

      - name: Copy Docker Compose Files to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          APP_PATH: ${{ secrets.APP_PATH }}
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no docker-compose.yml $USER@$HOST:$APP_PATH/

      - name: Deploy and Start Docker Services
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          APP_PATH: ${{ secrets.APP_PATH }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USER@$HOST "
            cd $APP_PATH &&
            docker-compose up -d
          "

      - name: Verify Elasticsearch Health
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USER@$HOST "
            curl -X GET 'localhost:9200/_cluster/health?pretty'
          "

      - name: Run WordsGenerator.py on EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          APP_PATH: ${{ secrets.APP_PATH }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USER@$HOST "
            cd $APP_PATH &&
            /usr/bin/python3 WordsGenerator.py
          "
